### ISSUE TITLE
fix junit tests

### ISSUE THREAD

**Issue by Wouter1** [INFLUENCEorg/aienvs#39]
There are a few non-working junit tests

Alex asked to check and fix them

**Comment by Wouter1** [comment]
Yes, FAILED (failures=2, errors=2)

First
```
ERROR: test_new_traffic (test.testSumoGymAdapter.testSumoGymAdapter)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/wouter/git/aienvs/test/testSumoGymAdapter.py", line 31, in test_new_traffic
    env = SumoGymAdapter(parameters)
  File "/home/wouter/git/aienvs/aienvs/Sumo/SumoGymAdapter.py", line 71, in __init__
    self.seed(parameters['seed'])  # in case no seed is given
KeyError: 'seed'
```

**Comment by Wouter1** [comment]
analysis, previously we called self.seed(42) which matched the SumoGymAdapter default seed. Jinke changed the call to the current self._seed(parameters['seed']) I think because he needed it for something

**Comment by Wouter1** [comment]
What should be happening is that default parameters are used if not set by the user.
I'll fix it acordingly

**Comment by Wouter1** [comment]
Second issue
```
FAIL: testListener (test.runners.testEpisode.testEpisode)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/wouter/git/aienvs/test/runners/testEpisode.py", line 50, in testListener
    listener.notifyChange.assert_called_once_with({'actions': {0:0}, 'observation': 'start_obs', 'reward':0, 'done':False})
  File "/usr/lib/python3.6/unittest/mock.py", line 825, in assert_called_once_with
    return self.assert_called_with(*args, **kwargs)
  File "/usr/lib/python3.6/unittest/mock.py", line 814, in assert_called_with
    raise AssertionError(_error_message()) from cause
AssertionError: Expected call: notifyChange({'actions': {0: 0}, 'observation': 'start_obs', 'reward': 0, 'done': False})
Actual call: notifyChange({'key': 'transition', 'actions': {0: 0}, 'observation': 'start_obs', 'reward': 0, 'done': False})
```

**Comment by Wouter1** [comment]
Someone added a key to the notifyChange call, but forgot to fix the test.

**Comment by Wouter1** [comment]
Issue 3
```
FAIL: testListener (test.runners.testExperiment.test_Experiment)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/wouter/git/aienvs/test/runners/testExperiment.py", line 46, in testListener
    self.assertEquals(30, len(listener.notifyChange.mock_calls))
AssertionError: 30 != 60

```

**Comment by Wouter1** [comment]
Something apparently changed in Experiment, causing more calls to our listener.

**Comment by Wouter1** [comment]
There are more calls to the listener now, we get something like

>CallList: [call({'key': 'transition', 'actions': <Mock name='mock.step()' id='139875469724248'>, 
 'observation': <Mock name='mock.reset()' id='139875469724024'>, 'reward': 0, 'done': False}),
 call({'key': 'episodic_return', 'step': 1, 'episode': 1, 'episodic_return': 3.0}),
 call({'key': 'transition', 'actions': <Mock name='mock.step()' id='139875469724248'>, 
  'observation': <Mock name='mock.reset()' id='139875469724024'>, 'reward': 0, 'done': False}),
 call({'key': 'episodic_return', 'step': 2, 'episode': 2, 'episodic_return': 3.0}),
 call({'key': 'transition', 'actions': <Mock name='mock.step()' id='139875469724248'>, 
  'observation': <Mock name='mock.reset()' id='139875469724024'>, 'reward': 0, 'done': False}),
 call({'key': 'episodic_return', 'step': 3, 'episode': 3, 'episodic_return': 3.0}),
 call({'key': 'transition', 'actions': <Mock name='mock.step()' id='139875469724248'>, 
  'observation': <Mock name='mock.reset()' id='139875469724024'>, 'reward': 0, 'done': False}),
 call({'key':...

**Comment by Wouter1** [comment]
Someone hooked up all episode details also to the listener of the experiment.
I assume this was the intention and will just fix the test  to check at least 30 calls were made

**Comment by Wouter1** [comment]
Python junit does not complain anymore now
But the pyunit tab in Eclipse still shows 6 errors??

**Comment by Wouter1** [comment]
First Eclipse error 
```
Traceback (most recent call last):
  File "/home/wouter/eclipse/plugins/org.python.pydev.core_7.1.0.201902031515/pysrc/_pydev_runfiles/pydev_runfiles.py", line 468, in __get_module_from_str
    mod = __import__(modname)
  File "/home/wouter/eclipse/plugins/org.python.pydev.core_7.1.0.201902031515/pysrc/setup.py", line 44, in <module>
    data_files.append(('pydevd_attach_to_process', [os.path.join('pydevd_attach_to_process', f) for f in os.listdir('pydevd_attach_to_process') if accept_file(f)]))
FileNotFoundError: [Errno 2] No such file or directory: 'pydevd_attach_to_process'
ERROR: Module: setup could not be imported (file: /home/wouter/git/aienvs/setup.py).

```

**Comment by Wouter1** [comment]
That bug is originating from org.python.pydev.core. Seems a system bug? I can not fix it.

**Comment by Wouter1** [comment]
Next is
```
Traceback (most recent call last):
  File "/home/wouter/eclipse/plugins/org.python.pydev.core_7.1.0.201902031515/pysrc/_pydev_runfiles/pydev_runfiles.py", line 468, in __get_module_from_str
    mod = __import__(modname)
  File "/home/wouter/git/aienvs/test/tesEnvironmentFactory.py", line 1, in <module>
    from LoggedTestCase import LoggedTestCase
ModuleNotFoundError: No module named 'LoggedTestCase'
ERROR: Module: test.tesEnvironmentFactory could not be imported (file: /home/wouter/git/aienvs/test/tesEnvironmentFactory.py).



```

**Comment by Wouter1** [comment]
correct import is
```
from test.LoggedTestCase import LoggedTestCase
```

fixed

**Comment by Wouter1** [comment]
Same problem in testUtils fixed

**Comment by Wouter1** [comment]
next
```
Traceback (most recent call last):
  File "/home/wouter/eclipse/plugins/org.python.pydev.core_7.1.0.201902031515/pysrc/_pydev_runfiles/pydev_runfiles.py", line 468, in __get_module_from_str
    mod = __import__(modname)
  File "/home/wouter/git/aienvs/aienvs/SimulatedEnvironment.py", line 1, in <module>
    from aienvs.Env import Env
ModuleNotFoundError: No module named 'aienvs.Env'
ERROR: Module: aienvs.SimulatedEnvironment could not be imported (file: /home/wouter/git/aienvs/aienvs/SimulatedEnvironment.py).



```

**Comment by Wouter1** [comment]
```
from aienvs.Env import Env
```

should be
```
from aienvs.Env import Env
```

**Comment by Wouter1** [comment]
```
Traceback (most recent call last):
  File "/home/wouter/eclipse/plugins/org.python.pydev.core_7.1.0.201902031515/pysrc/_pydev_runfiles/pydev_runfiles.py", line 468, in __get_module_from_str
    mod = __import__(modname)
  File "/home/wouter/git/aienvs/aienvs/Warehouse/warehouse.py", line 1, in <module>
    from warehouseItem import WarehouseItem
ModuleNotFoundError: No module named 'warehouseItem'
ERROR: Module: aienvs.Warehouse.warehouse could not be imported (file: /home/wouter/git/aienvs/aienvs/Warehouse/warehouse.py).



```

**Comment by Wouter1** [comment]
Fixed the warehouse imports (multiple imports were assuming the code runs in the warehouse directory instead of root).

**Comment by Wouter1** [comment]
@czechows 

I found a pieces of code that were basically doing incorrect imports and thus would never run. 

However there are no junit tests attached to these codes, and therefore these problems were never reported. At least not if you do command line python development. I found some Eclipse markers on these codes  but you really have to look for them even in Eclipse

Were you aware of these issues? Basically python code can even contain syntax errors and never load. But that problem will never be reported until the file is at least imported somewhere.

**Comment by Wouter1** [comment]
Found a fiile aienvs/Warehouse/test.py. Making separate ticket for that.

**Comment by Wouter1** [comment]
Warehouse has another issue
```
Traceback (most recent call last):
  File "/home/wouter/eclipse/plugins/org.python.pydev.core_7.1.0.201902031515/pysrc/_pydev_runfiles/pydev_runfiles.py", line 468, in __get_module_from_str
    mod = __import__(modname)
  File "/home/wouter/git/aienvs/aienvs/Warehouse/test.py", line 3, in <module>
    warehouse = Warehouse()
  File "/home/wouter/git/aienvs/aienvs/Warehouse/warehouse.py", line 19, in __init__
    parameters = read_parameters('warehouse')
NameError: name 'read_parameters' is not defined
ERROR: Module: aienvs.Warehouse.test could not be imported (file: /home/wouter/git/aienvs/aienvs/Warehouse/test.py).



```

**Comment by Wouter1** [comment]
I don't know what is going on there and put it in separate ticket #42 that can be solved separately (since that problem is not attached to any unit tests FAIK)

That completes this ticket.

**Comment by czechows** [comment]
> @czechows
> 
> I found a pieces of code that were basically doing incorrect imports and thus would never run.
> 
> However there are no junit tests attached to these codes, and therefore these problems were never reported. At least not if you do command line python development. I found some Eclipse markers on these codes but you really have to look for them even in Eclipse
> 
> Were you aware of these issues? Basically python code can even contain syntax errors and never load. But that problem will never be reported until the file is at least imported somewhere.

@Wouter1
So I suppose some of the team members started using the repo more actively, and pushed some half-finished work with unresolved imports / non-working code. This is not great but we can live with that. Nice that you found it. You can use "git blame" and make tickets for them so they can take care of it after their conference deadline this week (and also perhaps make a CAPS LOCK comment in the code that this will fail). Thanks in advance

**Comment by Wouter1** [comment]
@czechows "blame" sounds like pointing to a person to tell him he did something wrong. It would be better to assign people to this that know most of it/are in best position to fix it. 

Also I already fixed the import issues. So no need for new tickets/blame/etc

The point that you might consider is that people apparently do not make/update unit tests and thus have no clue if their code even loads. Maybe it does with some hacks on their own machines, but not for others unless they also start figuring out the specific hacks needed for that

**Comment by czechows** [comment]
@Wouter1 thanks for fixing it.

```git blame``` is just a name of the command-line tool (I think it is also somewhere in github). There is no pointing, the point is that you want to find the author of the code as he is the most likely person to be able to fix it. If you are able to figure out and fix it yourself, that's even better.

If there is anything that you can't figure, I agree that tickets may come off as creating too much urgency, you can also just send them an e-mail to make them aware of the issue.

As for unit tests, many researchers simply skip them to save time. They verify that the code loads e.g. by importing it into their run script of whatever experiment they needed the functionality for. I have been guilty of this in the past too.

**Comment by Wouter1** [comment]
@czechows 

>As for unit tests, many researchers simply skip them to save time. They verify that the code loads e.g. by importing it into their run script of whatever experiment they needed the functionality for. I have been guilty of this in the past too.

This is bad practice  especially when combined with python. Only the researcher runs that script and thus effectively tests his code. The minute someone else refactors, the researcher's code will break. With python, no alarm bells will ring until that researcher pulls an update and retries to run his script. That may be months and multiple refactors later and it may prove impossible to figure out how to fix his code by then.

In java, the IDE will give compiler errors even for unused code and the refactorer will then also fix that. So it would be much more robust with such research behaviour.

I think it is especially bad if you have committed working code and that code is not working when you come back to it a few months later. Maybe people in the python world see that differently :-/

**Comment by czechows** [comment]
Yes I am exactly aware of the problems. I think this is not that much of a question of python vs java (though strong typing would help), as of priorities. Making code tested and maintainable requires time and a researcher gets no credit for putting effort on that, rather than starting new projects..
