### ISSUE TITLE
test examples

### ISSUE THREAD

**Issue by Wouter1** [INFLUENCEorg/aienvs#44]
On 03/06/2020 17:12, Aleksander Czechowski wrote:
> 2. Revisit the examples directories in aienvs and aiagents.
> All examples should be executable by running "python3 file.py" (or eclipse equivalent..)
> Examples may take much longer than unit tests, so you don't need to run them to the end -- it is enough to kill them after few seconds of execution
>
> Some examples may fail because they are outdated in one way or another, and I think we haven't looked into these directories in a while

**Comment by Wouter1** [comment]
@czechows is it correct that there are no examples in aienvs?
I see an aienvs/examples directory but it does not contain .py files

**Comment by czechows** [comment]
@Wouter1 it could be that all were moved to aiagents when you were making aienvs independent of aiagents imports.

**Comment by Wouter1** [comment]
@czechows  ok I then close this and just fix this in aiagents.
